name: ai-news (daily batch)

on:
  schedule:
    - cron: '12 0 * * *' # 09:12 JST
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ai-news-daily
  cancel-in-progress: false

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build from RSS (past 7 days, max 20; JP columns; save fulltext)
        run: |
          npm run build:news -- --rss --since-days 7 --max 20 --jp-columns --save-fulltext

      - name: Generate weekly/monthly indices (JST-aware)
        run: |
          set -e
          DOW=$(TZ=Asia/Tokyo date +%u)  # 1..7 (Mon=1)
          DOM=$(TZ=Asia/Tokyo date +%d)  # 01..31

          if [ "$DOW" = "1" ]; then
            echo "Monday JST → generate weekly index"
            node scripts/pick_ai_week.mjs
          else
            echo "Not Monday JST → skip weekly"
          fi

          if [ "$DOM" = "01" ]; then
            echo "1st of month JST → try monthly index (optional)"
            npm run -s pick:month || true
          fi

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(news): daily batch" || echo "no changes"
          git push
