name: inbox from Discord (via Dify) 

on:
  repository_dispatch:
    types: [inbox_url]

permissions:
  contents: write

jobs:
  oneoff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - name: Append to inbox & build 1
        run: |
          echo "- [ ] ${{ github.event.client_payload.url }}" >> sources/url_inbox.md
          node scripts/build_from_clips.mjs --max 1 --jp-columns --save-fulltext
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(news): process 1 URL from repo_dispatch" || echo "no changes"
          git push
