name: ai-news (repo_dispatch one-off)

on:
  repository_dispatch:
    types: [ai-news-url]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ai-news-repo-dispatch
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Use npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node24-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node24-

      - name: Install
        run: npm ci

      # 追加①: inboxファイルを必ず用意 & ペイロードをログ出し
      - name: Prepare inbox & show payload
        run: |
          mkdir -p sources
          touch sources/url_inbox.md
          echo "payload URL = '${{ github.event.client_payload.url }}'"

      - name: Append to inbox (when repository_dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          URL="${{ github.event.client_payload.url }}"
          if [ -n "$URL" ]; then
            echo "- [ ] $URL" >> sources/url_inbox.md
            echo "appended to sources/url_inbox.md"
          else
            echo "no url payload, skip append"
          fi

      # 追加②: いまのリポの状態を軽く確認（デバッグ用）
      - name: Show tree (debug)
        run: |
          ls -la
          echo "--- sources/ ---"
          ls -la sources || true

      - name: Build (max 1, JP columns, save fulltext)
        run: npm run build:news -- --max 1 --jp-columns --save-fulltext

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(news): process 1 URL from repo_dispatch" || echo "no changes"
          git push
