name: "inbox from Discord (via Dify)"

on:
  repository_dispatch:
    types: [inbox_url]

permissions:
  contents: write

concurrency:
  group: url-inbox-md
  cancel-in-progress: false

jobs:
  inbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show incoming payload
        run: |
          echo "Incoming URLs(JSON):"
          echo '${{ toJson(github.event.client_payload.urls) }}'

      - name: Insert into sources/url_inbox.md
        shell: bash
        run: |
          set -euo pipefail
          FILE="sources/url_inbox.md"
          mkdir -p "$(dirname "$FILE")"
          TODAY="## $(TZ=Asia/Tokyo date '+%Y年%m月%d日 (%a)')"
          # toJson(github.event) を jq に食わせる
          mapfile -t URLS < <(jq -r '.client_payload.urls[]' <<< '${{ toJson(github.event) }}' || true)

          [[ -f "$FILE" ]] && CONTENT="$(cat "$FILE")" || CONTENT=""
          if ! grep -q "^${TODAY}$" <<<"$CONTENT"; then
            CONTENT="${TODAY}\n\n- [ ] 追加URL\n\n${CONTENT}"
          fi
          for u in "${URLS[@]}"; do
            grep -q "^- \[.\] ${u}$" <<<"$CONTENT" || CONTENT="${TODAY}\n\n- [ ] ${u}\n${CONTENT#${TODAY}}"
          done
          printf "%b" "$CONTENT" > "$FILE"

      - name: Commit & push (with rebase)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sources/url_inbox.md
          git commit -m "chore(inbox): append URLs from Dify" || { echo "No changes"; exit 0; }
          # 軽い競合回避
          current_branch="${GITHUB_REF_NAME}"
          git pull --rebase origin "$current_branch" || true
          git push
