name: ingest
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "URL（スペース/改行/カンマ区切りOK）"
        required: false
        type: string
  repository_dispatch:
    types: [inbox_url]

permissions:
  contents: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20.x' }
      - run: npm i

      - name: Debug payload & files
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "--- event payload ---"
          cat "$GITHUB_EVENT_PATH" || true
          echo "--- scripts dir ---"
          ls -la scripts || true

      - name: Ingest URLs
        run: |
          if [ -n "${{ github.event.inputs.urls }}" ]; then
            node scripts/ingest.js --urls "${{ github.event.inputs.urls }}"
          else
            node scripts/ingest.js
          fi
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Commit & Push (items.json / queue.jsonl)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/data/items.json content/data/queue.jsonl || true
          git commit -m "ingest: update data ($(date -u +%Y-%m-%dT%H:%M:%SZ))" || echo "no changes"
          git push || true
