name: Summarize URL (Gemini)

on:
  workflow_dispatch:
    inputs:
      url:
        description: "単発URL（seed_fileと同時指定不可）"
        required: false
        type: string
        default: ""
      seed_file:
        description: "シード一覧のパス（urlと同時指定不可） 例: seeds.txt"
        required: false
        type: string
        default: ""
      style:
        description: "出力スタイル"
        required: false
        type: string
        default: "general"
      lang:
        description: "言語"
        required: false
        type: string
        default: "ja"
      model:
        description: "Geminiのモデル名（未指定なら repo var GEMINI_MODEL を使用）"
        required: false
        type: string
        default: ""

permissions:
  contents: write

concurrency:
  group: summarize-${{ github.ref }}
  cancel-in-progress: true

jobs:
  summarize:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }} # ←Secrets名に合わせて（GEMINI_API_KEYならここも変更）
      GEMINI_MODEL:   ${{ github.event.inputs.model != '' && github.event.inputs.model || vars.GEMINI_MODEL }}
      STYLE:          ${{ github.event.inputs.style != '' && github.event.inputs.style || 'general' }}
      LANG:           ${{ github.event.inputs.lang  != '' && github.event.inputs.lang  || 'ja' }}
      URL:            ${{ github.event.inputs.url }}
      SEED_FILE:      ${{ github.event.inputs.seed_file }}
      DOCS_PATH:      ${{ vars.DOCS_PATH || 'docs/ai-news-bot' }}
      PUBLISH_TO_DOCS: ${{ vars.PUBLISH_TO_DOCS || 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run summarizer (Gemini via Google AI Studio)
        shell: bash
        run: |
          set -euo pipefail

          # どちらか片方だけ許可
          if [[ -n "${URL}" && -n "${SEED_FILE}" ]]; then
            echo "::error::url と seed_file は同時指定できません。片方だけにしてください。"
            exit 1
          fi
          if [[ -z "${URL}" && -z "${SEED_FILE}" ]]; then
            echo "::error::url か seed_file のどちらかは必須です。"
            exit 1
          fi

          mkdir -p "${DOCS_PATH}"

          CMD=(node scripts/summarize.mjs
               --style "${STYLE}"
               --lang "${LANG}"
               --gemini-model "${GEMINI_MODEL}"
               --outdir "${DOCS_PATH}")

          if [[ -n "${URL}" ]]; then
            CMD+=(--url "${URL}")
          else
            CMD+=(--seed-file "${SEED_FILE}")
          fi

          printf 'RUN:'; printf ' %q' "${CMD[@]}"; echo
          "${CMD[@]}"

      - name: Upload artifact (summary)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: |
            ${{ env.DOCS_PATH }}/**/*.md
            ${{ env.DOCS_PATH }}/**/*.html
          if-no-files-found: warn
          retention-days: 14

      - name: Publish to docs (optional)
        if: env.PUBLISH_TO_DOCS == 'true'
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add "${DOCS_PATH}"
          if ! git diff --cached --quiet; then
            git commit -m "docs: update summaries from run ${GITHUB_RUN_ID}"
            git push
          else
            echo "No changes to commit."
          fi
