name: summarize-url

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to summarize (単発)"
        required: false
        default: ""
      seed_file:
        description: "バッチ用のURLリスト（改行区切り）へのパス（例: seeds.txt）"
        required: false
        default: ""
      style:
        description: "summary style (general|tech|research|policy)"
        required: false
        default: "general"
      lang:
        description: "要約言語 (ja|en)"
        required: false
        default: "ja"
      retries:
        description: "fetch retries"
        required: false
        default: "2"
      timeout_ms:
        description: "fetch timeout (ms)"
        required: false
        default: "20000"
  # schedule:
  #   - cron: "0 0 * * *" # JST 9:00

permissions:
  contents: read

concurrency:
  group: summarize-url
  cancel-in-progress: true

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          set -e
          npm ci --no-audit --no-fund || npm i --no-audit --no-fund
          node -e "require.resolve('jsdom');require.resolve('@mozilla/readability');" \
            || npm i jsdom @mozilla/readability --no-audit --no-fund

      - name: Run summarizer (Gemini via Google AI Studio)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL:  ${{ vars.GEMINI_MODEL }}
        run: |
          set -euo pipefail
          OUTDIR="summary/${{ github.run_id }}"
          URL_INPUT="${{ inputs.url }}"
          SEED_INPUT="${{ inputs.seed_file }}"
          STYLE="${{ inputs.style }}"
          LANG="${{ inputs.lang }}"
          RETRIES="${{ inputs.retries }}"
          TIMEOUT_MS="${{ inputs.timeout_ms }}"

          ARGS=( --outdir "$OUTDIR" --style "$STYLE" --lang "$LANG" --retries "$RETRIES" --timeout "$TIMEOUT_MS" )
          if [ -n "$URL_INPUT" ]; then ARGS+=( --url "$URL_INPUT" ); fi
          if [ -n "$SEED_INPUT" ]; then ARGS+=( --seed-file "$SEED_INPUT" ); fi

          node scripts/summarize.mjs "${ARGS[@]}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary/**
          if-no-files-found: error
          retention-days: 14
